name: Install EarthBuild
description: Install EarthBuild v0.8.17 (earth-linux-amd64) to ~/.local/bin/earth
inputs: {}
runs:
  using: composite
  steps:
    - run: |
        cd "$(mktemp -d)"

        # https://github.com/EarthBuild/earthbuild/blob/main/release/apt-repo/earthbuild-pgp-public.pgp
        cat > earthbuild.pgp <<EOS
        -----BEGIN PGP PUBLIC KEY BLOCK-----

        mQINBGjK6e4BEADGhdw29msnPUxk4LTGkJtbcssG04taVHp4uH9SI1zT4dT7Qo0h
        DvK3HHiXP+xRVwBjtj4p3zw1zM7d1ZWeELMe92FlIcaGUEezuOQMsXWgwcW6gy6x
        OvX4zXeWqhcvWbjuFjwms4Oao6wOlRxitFkZOrHAUoMNZyVpbsCLbxVgKMNyJ+pK
        mvazaiNBGQ1Nb3KNloXY9H0T68wQeBDWWCCPFn/RvFB+23VqvYx5CM43RhpLIW+8
        pX0rfqsBmZJSuHLXPWpF+wxTKaAbCANZifhrkc7ZBPTBXWjSnvyagUe9KpvDHhga
        e6KGDwWqN7W9R2kv6INLYEZ0WA74OpFg08acGVGquFyvnnZG7ViooOCfL29L83i+
        MaFC9+pfPEh0nuQ3JLB/gHS2EDVfgholeYUG8rEzb/iWoUfi19ZhoIU9+KGpwctg
        4M+gM/Y9J4UuJreGVFap6XZ3Imo7aN4qNuMf2DeaJZ3z9rsjngkug+xfeSZk7n4m
        n8KAGHkJb5AGNph0aWI/VJYeCQT4P1TGo9HkmuL41C9XX4K+mDvsvbPvQtMpAom3
        +89waakBqvzrceBu4S74t0ibW3piERzkTOSQbiTI9YM82jq/vKF6aKqwmQOlGX/g
        ayMILIgkeEgqMkZqsFA5/bmjoGKEqHmdVTvzV/jSwjyrCgKLbrkocTyqCwARAQAB
        tCVlYXJ0aGJ1aWxkIDx3ZWJtYXN0ZXJAZWFydGhidWlsZC5kZXY+iQJOBBMBCgA4
        FiEECJAEebmBr3wyyLkYYEyIef+DwmAFAmjK6e4CGy8FCwkIBwIGFQoJCAsCBBYC
        AwECHgECF4AACgkQYEyIef+DwmAGqRAAiquwY5BpGAqKA4tisW0l740mskwCK4Kl
        DtmHCY6Emc4zwOzmVFkjBIJj+C2r5IpYCnE8stYrWbHE7EobH2TRn4yr8I7dGWag
        GNYYwCm6oSRB8EqgqjMgvUvWijndlAv05GQflC12SUKbQ70N1MWuZuPNlS5XgLUF
        EEJVRbUg+14qU8bxe6pYDshHdwIQFIR/a6ctv9kX/L5NHrPg5/RkGQZnQ8Mv+v1Q
        x/ZXskEeip+lOb0EMDbhvyP4LhWLlXReUmtYTghkzr82r1jcqilv6BOSqKXCXLvr
        sewp7h/OLT11gZcegrWU3ZzDGR/uZFenH5jghOmBWPnRlmjbThJhy6fkajQrjB2K
        X2rXGKe4/ozmCTfvj5GeFlLY5JJn0sb74ad59bw1BOI0/4TXcNHgJIka9o+sKL3s
        xTvzo+BKaoeJgO5oWymsjOTmlnjVek9uZIfopfnzyVFyMDi0Eou1nrgp9cJMfnQy
        efRUTCAWEbqDlrN+XWM4RvGS/CHYXnIhcqse18daasmKuAAgLTVYsfLR9XeuRb0Y
        Ac1SOVaR7iSYpr/YroIZtrcItZ5mlpANFvigYkI+x6qHj7imJU3/X1fEVri5WBEZ
        WdXYWLXfYcaBOaFh+4Ykj8Hv5Cdw5aMz5hyehkfsiRZ8/hLvOIA2SuRhYVChNAG0
        fChvHjF27Gk=
        =HUBY
        -----END PGP PUBLIC KEY BLOCK-----
        EOS

        gpg --no-tty --import earthbuild.pgp
        gpg --no-tty --command-fd 0 --edit-key 08900479B981AF7C32C8B918604C8879FF83C260 trust <<EOS
        5
        y
        EOS

        curl --location --parallel --parallel-immediate \
          -O https://github.com/EarthBuild/earthbuild/releases/download/v0.8.17/checksum.asc \
          -O https://github.com/EarthBuild/earthbuild/releases/download/v0.8.17/earth-linux-amd64

        gpg --no-tty --verify checksum.asc
        gpg --no-tty --output - checksum.asc | grep earth-linux-amd64 | sha256sum --check

        mkdir -p ~/.local/bin
        mv earth-linux-amd64 ~/.local/bin/earth
        chmod +x ~/.local/bin/earth
        EARTHLY_DISABLE_ANALYTICS=true earth config global '{disable_analytics: true, disable_log_sharing: true}'
        earth --version
      shell: bash
